name = "hdlean"
version = "0.1.0"
defaultTargets = ["hdlean"]
testDriver = "test"

#[[require]]
#name = "mathlib"
#scope = "leanprover-community"

#[[require]]
#name = "Canonical"
#scope = "chasenorman"

[[lean_lib]]
name = "Hdlean"

[[lean_lib]]
name = "Compiler"

[[lean_exe]]
name = "hdlean"
root = "Main"
supportInterpreter = true # needed for evalConst

[[lean_exe]]
name = "test"
root = "Test"
supportInterpreter = true # needed for evalConst

